power = {'BUSES': {'Area': 11.3901,
           'Bus/Area': 11.3901,
           'Bus/Gate Leakage': 0.0305562,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.318638,
           'Bus/Subthreshold Leakage with power gating': 0.119489,
           'Gate Leakage': 0.0305562,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.318638,
           'Subthreshold Leakage with power gating': 0.119489},
 'Core': [{'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0147636,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.214285,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0830358,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.340561,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.381367,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 5.66452,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 2247.69,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 2253.74,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.20041,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.324016,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202649.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 2.95221,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0956137,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 2.62255,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.805602,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 5.57476,
           'Execution Unit/Register Files/Runtime Dynamic': 0.901216,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.485985,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 7.21058,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 2262.73,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00142409,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00142409,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00123122,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00047162,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000863611,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00494302,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0139811,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 23.9772,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 5.2368,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.731968,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.196297,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4058.37,
           'Instruction Fetch Unit/Runtime Dynamic': 24.9244,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.8166,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.25425,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0834523,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0834525,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 5.78573,
           'Load Store Unit/Runtime Dynamic': 1.74927,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.205779,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.411559,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0730317,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0737973,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.228575,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0566253,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.64277,
           'Memory Management Unit/Runtime Dynamic': 0.13043,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209273.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 1.28608,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.139996,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 21.9734,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 23.3995,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 2312.94,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0147636,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.214285,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0830358,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.340561,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.363507,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 5.39923,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 2134.97,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 2140.73,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.190445,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.312425,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202649.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 2.95221,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0911362,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 2.58563,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.767874,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 5.53784,
           'Execution Unit/Register Files/Runtime Dynamic': 0.85901,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.479626,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 6.85457,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 2149.31,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00134358,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00134358,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00116164,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000444978,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000823175,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00467198,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.01319,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 22.8543,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 4.99155,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.685767,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.187104,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4057.99,
           'Instruction Fetch Unit/Runtime Dynamic': 23.745,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.71386,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.20608,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0801283,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0801284,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 5.60456,
           'Load Store Unit/Runtime Dynamic': 1.68138,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.197583,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.395166,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0701227,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0708883,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.21787,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0530515,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.5957,
           'Memory Management Unit/Runtime Dynamic': 0.123948,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209273.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 1.28608,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.133796,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 20.944,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 22.3639,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 2197.23,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.008476820608879517,
          'Runtime Dynamic': 0.008476820608879517,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L2': [{'Area': 22.2273,
         'Gate Leakage': 0.0518439,
         'Peak Dynamic': 0.184209,
         'Runtime Dynamic': 0.103954,
         'Subthreshold Leakage': 2.01996,
         'Subthreshold Leakage with power gating': 0.908099}],
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.000490098,
         'Runtime Dynamic': 0.000163323,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 3648.97,
               'Gate Leakage': 11.3965,
               'Peak Dynamic': 418546.0,
               'Peak Power': 418719.0,
               'Runtime Dynamic': 4510.27,
               'Subthreshold Leakage': 161.973,
               'Subthreshold Leakage with power gating': 70.017,
               'Total Cores/Area': 3553.45,
               'Total Cores/Gate Leakage': 11.2657,
               'Total Cores/Peak Dynamic': 418546.0,
               'Total Cores/Runtime Dynamic': 4510.16,
               'Total Cores/Subthreshold Leakage': 152.834,
               'Total Cores/Subthreshold Leakage with power gating': 65.205,
               'Total L2s/Area': 22.2273,
               'Total L2s/Gate Leakage': 0.0518439,
               'Total L2s/Peak Dynamic': 0.184209,
               'Total L2s/Runtime Dynamic': 0.103954,
               'Total L2s/Subthreshold Leakage': 2.01996,
               'Total L2s/Subthreshold Leakage with power gating': 0.908099,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 0.000490098,
               'Total L3s/Runtime Dynamic': 0.000163323,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 173.37,
               'Total NoCs/Area': 11.3901,
               'Total NoCs/Gate Leakage': 0.0305562,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.318638,
               'Total NoCs/Subthreshold Leakage with power gating': 0.119489}}