power = {'BUSES': {'Area': 16.0146,
           'Bus/Area': 16.0146,
           'Bus/Gate Leakage': 0.0429624,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.448008,
           'Bus/Subthreshold Leakage with power gating': 0.168003,
           'Gate Leakage': 0.0429624,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.448008,
           'Subthreshold Leakage with power gating': 0.168003},
 'Core': [{'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00982005,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.210402,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0552332,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.32833,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 1.0006,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 14.862,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 4831.64,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 4847.5,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.549691,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.491418,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202649.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 1.96373,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.250865,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 3.28707,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 2.11367,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 5.25081,
           'Execution Unit/Register Files/Runtime Dynamic': 2.36453,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.588948,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 12.2282,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 4863.13,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00826083,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00826083,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00713967,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00273353,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00226589,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0259272,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0811871,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 62.9092,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 9.16413,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 2.41371,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.515026,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4064.44,
           'Instruction Fetch Unit/Runtime Dynamic': 65.9451,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 5.58258,
           'Load Store Unit/Data Cache/Runtime Dynamic': 2.09817,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.140586,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.140586,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 8.89984,
           'Load Store Unit/Runtime Dynamic': 2.93209,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.346661,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.693324,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.123031,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.123464,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.399995,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.186716,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 4.43925,
           'Memory Management Unit/Runtime Dynamic': 0.310186,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209283.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.855456,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.352416,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 57.5791,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 58.7869,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 4991.1,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00982005,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.210402,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0552332,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.32833,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 1.13757,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 16.8966,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 5479.79,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 5497.82,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.626055,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.542158,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202649.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 1.96373,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.285207,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 3.57,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 2.40302,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 5.53373,
           'Execution Unit/Register Files/Runtime Dynamic': 2.68823,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.637675,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 13.7867,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 5515.38,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00949867,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00949867,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00820932,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00314295,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00257608,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0297827,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0933595,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 71.5212,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 9.16413,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 2.76771,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.58553,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4064.44,
           'Instruction Fetch Unit/Runtime Dynamic': 74.9976,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 6.10789,
           'Load Store Unit/Data Cache/Runtime Dynamic': 2.35186,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.157581,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.157581,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 9.82615,
           'Load Store Unit/Runtime Dynamic': 3.28658,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.388568,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.777136,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.137904,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.138394,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.399995,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.2141,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 4.62517,
           'Memory Management Unit/Runtime Dynamic': 0.3525,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209285.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.855456,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.399968,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 65.4602,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 66.7157,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 5660.73,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00982005,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.210402,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0552332,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.32833,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 1.14174,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 16.9584,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 5499.57,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 5517.67,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.628376,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.543714,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202649.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 1.96373,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.286251,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 3.5786,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 2.41182,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 5.54233,
           'Execution Unit/Register Files/Runtime Dynamic': 2.69807,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.639157,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 13.8345,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 5535.29,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00953622,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00953622,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00824179,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.0031554,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00258551,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0298997,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0937276,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 71.7831,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 9.16413,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 2.77834,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.587674,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4064.44,
           'Instruction Fetch Unit/Runtime Dynamic': 75.2727,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 6.12396,
           'Load Store Unit/Data Cache/Runtime Dynamic': 2.35878,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.158101,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.158101,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 9.8545,
           'Load Store Unit/Runtime Dynamic': 3.29658,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.38985,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.7797,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.138359,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.138836,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.399995,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.214922,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 4.63086,
           'Memory Management Unit/Runtime Dynamic': 0.353762,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209285.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.855456,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.401414,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 65.6999,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 66.9567,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 5681.17,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00982005,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.210402,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0552332,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.32833,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.993703,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 14.7597,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 4798.93,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 4814.68,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.545869,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.48885,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202649.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 1.96373,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.249136,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 3.27291,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 2.09911,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 5.23665,
           'Execution Unit/Register Files/Runtime Dynamic': 2.34824,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.58651,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 12.1493,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 4830.21,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00819844,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00819844,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00708567,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00271282,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00225028,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0257328,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0805763,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 62.4758,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 9.16413,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 2.39604,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.511477,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4064.44,
           'Instruction Fetch Unit/Runtime Dynamic': 65.4897,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 5.55603,
           'Load Store Unit/Data Cache/Runtime Dynamic': 2.08508,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.139727,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.139727,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 8.85302,
           'Load Store Unit/Runtime Dynamic': 2.9139,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.344543,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.689086,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.122279,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.12269,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.399995,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.185349,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 4.42985,
           'Memory Management Unit/Runtime Dynamic': 0.308045,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209283.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.855456,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.350023,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 57.1825,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 58.3879,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 4957.31,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.00902161336659732,
          'Runtime Dynamic': 0.00902161336659732,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L2': [{'Area': 22.2273,
         'Gate Leakage': 0.0518439,
         'Peak Dynamic': 0.217982,
         'Runtime Dynamic': 0.123417,
         'Subthreshold Leakage': 2.01996,
         'Subthreshold Leakage with power gating': 0.908099}],
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.000544553,
         'Runtime Dynamic': 0.000213829,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 7207.04,
               'Gate Leakage': 22.6747,
               'Peak Dynamic': 837136.0,
               'Peak Power': 837474.0,
               'Runtime Dynamic': 21290.4,
               'Subthreshold Leakage': 314.937,
               'Subthreshold Leakage with power gating': 135.294,
               'Total Cores/Area': 7106.89,
               'Total Cores/Gate Leakage': 22.5315,
               'Total Cores/Peak Dynamic': 837136.0,
               'Total Cores/Runtime Dynamic': 21290.3,
               'Total Cores/Subthreshold Leakage': 305.668,
               'Total Cores/Subthreshold Leakage with power gating': 130.41,
               'Total L2s/Area': 22.2273,
               'Total L2s/Gate Leakage': 0.0518439,
               'Total L2s/Peak Dynamic': 0.217982,
               'Total L2s/Runtime Dynamic': 0.123417,
               'Total L2s/Subthreshold Leakage': 2.01996,
               'Total L2s/Subthreshold Leakage with power gating': 0.908099,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 0.000544553,
               'Total L3s/Runtime Dynamic': 0.000213829,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 337.611,
               'Total NoCs/Area': 16.0146,
               'Total NoCs/Gate Leakage': 0.0429624,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.448008,
               'Total NoCs/Subthreshold Leakage with power gating': 0.168003}}